### ISSUE TITLE
Call `mimetypes.guess_type` with `strict=False`.

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.contenttype#14]
We might want in addition call `mimetypes.guess_type` with `strict=False`.

The documentation says that with the default `strict=True` only IANA registered mime types are taken into account. Thus, some types we have specified might be ignored.

_Originally posted by @d-maurer in https://github.com/zopefoundation/zope.contenttype/pull/13#pullrequestreview-1634879960_
            

To be fixed in `zope.contenttype.guess_content_type()`.

**Comment by sallner** [comment]
I have had a look into the subject. 

The non-strict MIME types can be found [here](https://github.com/python/cpython/blob/74978ae6c6797e501af6822b3b829fd06a78eadb/Lib/mimetypes.py#L585-L594). They are not so common and I do not know, if it is worth to add those to the general search.

The other question was, whether we find the MIME types added in this package only via `strict=False`. This can be negated, as we pass the `filenames` to the `__init__` with the default value of `strict=True` which [adds them to the ones found](https://github.com/python/cpython/blob/74978ae6c6797e501af6822b3b829fd06a78eadb/Lib/mimetypes.py#L201-L210) with `strict=True` (i.e. dict in `types_map[True]`).

The same is true [for adding](https://github.com/python/cpython/blob/74978ae6c6797e501af6822b3b829fd06a78eadb/Lib/mimetypes.py#L370-L379) the file to the `knownfiles` attribute.

So my estimation is, that we do not need to change anything. If we want to be more explicitly, we could use the `strict=True` parameter for the db init explicitly.

**Comment by icemac** [comment]
@sallner Thank you for your investigation.
Closing this issue as `won't fix` then.

**Comment by d-maurer** [comment]
@sallner I have looked at the code and can confirm your analysis: the `strict` parameter affects only the 8 type assignments in `mimetypes._default_mime_tpyes._common_types_default`. Nevertheless, I think we should use `strict=False`:
* Python's documentation says `strict=True` would restrict to IANA registered types, but this is not true. In fact, `strict` is based on data in Python source code not synchronized with the IANA registry: `application/rtf` is now IANA registered but would not be found (reliably) with `strict=True`.
* The definitions in `_common_types_default` are indeed common: e.g. the `midi` definitions are listed as MIME types on the Wikipedia pages describing `midi`. I think we should recognize those types.
* The `.xul` suffix is now IANA registered but with a different media type (`application/vnd.mozilla.xul+xml ` instead of `text/xul`). I do not think this is a big problem: the `_common` definitions have lower priority on lookup than the standard definitions; therefore, a corrected `.xul` definition from a different source (in my Linux system, it would come from `/etc/mime.type`) overrides the wrong one.

`strict=True` might have its worth if it were really based on current IANA definitions. But, this is not the case. I think we are usually interested to recognize all common types, even if not yet IANA registered.
