### ISSUE TITLE
Relying on the built-in mimetypes module can lead to issues

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/zope.contenttype#17]
Zope uses the `guess_content_type` function from this package in its default WebDAV PUT factory to correctly guess which Zope object to create given a name and the content body.

If you use a recent Linux version like the latest Ubuntu or RHEL-based distro a specific test in the Zope webdav tests that wants to make sure item names ending in `.pt` lead to creating Zope Page Templates now fails.

The first check is to call `mimetypes.guess_type` with the name of the object. On Windows, macOS and earlier Linux versions this call returns the tuple `(None, None)` for names ending in `.pt`, meaning there is no match. `zope.contenttype` then looks at the body and if it looks like HTML the right thing happens and Zope creates a Page Template. On recent Linux versions the check returns `('application/vnd.snesdev-page-table', None)`. Given this content type Zope creates a standard File object.

I am not sure where the problem should be solved. In `zope.contenttype` that blindly trusts the platform's built-in mime type guessing or in Zope itself?

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2024-5-17 00:37 -0700:
> ...
>If you use a recent Linux version like the latest Ubuntu or RHEL-based distro a specific test in the Zope webdav tests that wants to make sure item names ending in `.pt` lead to creating Zope Page Templates now fails.
>
>The first check is to call `mimetypes.guess_type` with the name of the object. On Windows, macOS and earlier Linux versions this call returns the tuple `(None, None)` for names ending in `.pt`, meaning there is no match. `zope.contenttype` then looks at the body and if it looks like HTML the right thing happens and Zope creates a Page Template. On recent Linux versions the check returns `('application/vnd.snesdev-page-table', None)`. Given this content type Zope creates a standard File object.
>
>I am not sure where the problem should be solved. In `zope.contenttype` that blindly trusts the platform's built-in mime type guessing or in Zope itself?

I think it should be implemented in `Zope` (because it integrates
"PageTemplate"s).

I propose the following approach:

 * We define a mime type for "PageTemplate"s, maybe
   `application/vnd.zopefoundation.page-template` (or `test/...`),
   and associate it with the extension ".pt".

 * We give `Zope` a `mime.types` file defining the `Zope` specific
   mime types (among them the new "PageTemplate" type)

 * We call `zope.contenttype.add_files()` with this file.


Zope is changed to create "PageTemplate" files when it sees its
"its" corresponding mime type.

**Comment by dataflake** [comment]
That's a good idea, I will close this issue and follow up in https://github.com/zopefoundation/Zope/issues/1212
